name: GitHub Hosted Runners

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print Ubuntu information
        run: |
          echo "OS: Ubuntu"
          echo "Hostname: $(hostname)"
          echo "Current user: $(whoami)"

  windows:
    runs-on: windows-latest
    steps:
      - name: Print Windows information
        shell: pwsh
        run: |
          Write-Host "OS: Windows"
          Write-Host "Hostname: $env:COMPUTERNAME"
          Write-Host "Current user: $env:USERNAME"

  macos:
    runs-on: macos-latest
    steps:
      - name: Print macOS information
        run: |
          echo "OS: macOS"
          echo "Hostname: $(hostname)"
          echo "Current user: $(whoami)"
